#!/bin/bash
#	rdp_nsupdate v2.0
#
#		This script updates the defualt names server with the hostname and ip address
#		including reverse lookup.  It support rhel 6 and rhel 7.
# 07-19-2013:	corrected config file use.
# 06/11/2014:	added full paths to ensure functionality independant of environment variables
# 06/30/2014:	moved tmp and log files to /tmp/ and added logging to /var/log/messages
# 06/30/2014:	added 7 day purge in /tmp to remove older tmp and log files
# 12/08/2014:	added full path to ifconfig line
# 02/25/2015:	corrected logging of ntpd sync
# 03/12/2017:	removed parametr and config file options; now uses ip from def route
# 10/11/2017:   forked from config channel on VA sat and removed ntp sync
#
TMP_FILE=$(date +"/tmp/rdp_nsupdate-%Y-%m%d-%H%M%S.tmp")
LOG_FILE=$(date +"/tmp/rdp_nsupdate-%Y-%m%d-%H%M%S.log")

IPADDR=$(ip -4 route get 1 | head -1 | awk '{ print $7}' | tr -d '\n')
IFS="." read -ra INARPA <<< "$IPADDR"

echo update add ${HOSTNAME} 86430 a ${IPADDR} >$TMP_FILE
echo send >>$TMP_FILE
echo update add ${INARPA[3]}.${INARPA[2]}.${INARPA[1]}.${INARPA[0]}.in-addr.arpa 86430 ptr    ${HOSTNAME} >>$TMP_FILE
echo send >>$TMP_FILE 

/usr/bin/nsupdate -v -d $TMP_FILE >>$LOG_FILE 2>&1

if [[ -x /bin/logger ]]; then
  /bin/logger -i -t rdp_nsupdate -f $LOG_FILE
fi
find /tmp/rdp_nsupdate* -type f -mtime +7 -exec rm {} \; 2>/dev/null
