---
- name: "Run RedHat Enterprise Linux 8 tasks"
  import_tasks: rhel8.yml
  when: ansible_distribution == "RedHat"
        and ansible_distribution_major_version == "8"

- name: "Run Oracle Unbreakable Linux 8 tasks"
  import_tasks: rhel8.yml
  when: ansible_distribution == "OracleLinux"
        and ansible_distribution_major_version == "8"
        