---
- name: nfs - latest cifs version installed
  yum:
    name: cifs-utils
    state: latest
  
- name: nfs - make mount point
  file:
    path: /mnt/share
    state: directory

- name: nfs - Set firewall rule to allow nfs  
  firewalld:
    zone: public
    service: samba
    permanent: true
    state: enabled

- name: nfs - Reload Firewall
  service: name=firewalld state=restarted

- name: nfs - mount cifs
  mount:
    path: /mnt/share
    src: //172.16.4.76/share
    fstype: cifs
    state: mounted
    opts: user=root,pass=1qazxsw2
