# Ansible Playbook
# Reviewed: 01/07/22
# added tags 01/07/22
#
# For:
# - rhel8

---
- name: timeout.yml - Set Tags
  tags:
  - timeout 
  block:

  - name: timeout.yml - Create tmux.conf
    copy:
      src: ../files/el8/etc/tmux.conf
      dest: /etc/
      backup: yes
      owner: root
      group: root
      mode: 0644