---
  - name: lamp.yml - Install the LAMP packages
    apt:
      name:
        - apache2
        - php
        - libapache2-mod-php
        - mariadb-server 
        - mariadb-client
        - php-mysql
        - phpmyadmin
      state: latest

  - name: lamp.yml - Create Test Page
    blockinfile: 
      path: /var/www/html/testphp.php
      create: yes
      backup: yes
      marker: "## {mark} Added For KJETT Security"
      owner: www-data
      group: www-data
      mode: 0644
      content: |
        <?php phpinfo(); ?>

  - name: lamp.yml - apache2 enabled and running
    service:
      name: apache2
      enabled: true
      state: started

  - name: lamp.yml - mariadb enabled and running
    service:
      name: mariadb
      enabled: true
      state: started
