# Ansible Playbook 
# Erik van Oudheusden erik@viking-armory.com
#
#

---
- name: snmp.yml - Set Tags
  tags:
  - snmp
  block:

  - name: snmp.yml - latest snmp version installed
    apt:
      name: snmpd
      state: latest

  - name: snmp.yml - Delete existing snmp conf file
    file: path=/etc/snmp/snmpd.conf
      state=absent

  - name: snmp.yml - Get distro file
    copy:
      src: ~/bin/Ansible/AnsibleRoles/pi/files/distro
      dest: /usr/bin/distro
      owner: root
      group: root
      mode: 0755
      
  - name: snmp.yml - Create snmpd.conf
    blockinfile: 
      path: /etc/snmp/snmpd.conf
      create: yes
      backup: yes
      marker: "## {mark} Added For Hohenfelsjoe Security"
      owner: root
      group: root
      mode: 0644
      content: |
        ###############################################################################
        #
        # snmpd.conf:
        #   Hohenfelsjoe SNMP Configuration.
        #
        ###############################################################################
        agentaddress udp:161
        #       sec.name            source          community
         
        com2sec InternalNetwork   192.168.1.0/24      LAN
        com2sec InternalNetwork   172.16.4.0/24       DMZ
        com2sec local               localhost           Local
         
        #       groupName       securityModel   securityName
        group   ReadOnlyGroup    v2c            InternalNetwork
        group   ReadOnlyGroup    v2c            local
         
         
        # Make at least  snmpwalk -v 1 localhost -c public system fast again.
        #       name           incl/excl     subtree         mask(optional)
        view    systemview    included   .1.3.6.1.2.1.1
        view    systemview    included   .1.3.6.1.2.1.25.1.1
        view    systemview    included   .1
         
        #       group           context sec.model sec.level prefix read         write   notif
        access  ReadOnlyGroup    ""      any       noauth    exact  systemview   none    none
         
        #               System information
        syslocation     NoneYa
        syscontact      root@localhost
        
        #This line allows Observium to detect the host OS if the distro script is installed
        extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro

  - name: snmp.yml - snmp enabled and running
    service:
      name: snmpd
      enabled: true
  #    state: started  

      
