# Ansible Playbook 
#
# Configure OpenSSH Server if Necessary

---
- name: ssh.yml - Set Tags
  tags:
  - ssh 
  block:

  - name: ssh.yml - latest sshd version installed
    apt:
      name: openssh-server
      state: latest

  - name: ssh.yml - Delete existing issue banner
    file: path=/etc/issue
      state=absent

  - name: ssh.yml - Delete existing issue.net banner
    file: path=/etc/issue.net
      state=absent

  - name: ssh.yml - Set issue.net banner
    copy:
      src: ../files/pi/issue
      dest: /etc/issue
      backup: yes
      owner: root
      group: root
      force: yes
        
  - name: ssh.yml - create sym link
    file:
      src: /etc/issue.net
      dest: /etc/issue
      owner: root
      group: root
      state: link

  - name: ssh.yml - Copy SSH Config
    copy:
      src: ../files/pi/sshd_config
      dest: /etc/ssh/sshd_config
      backup: yes
      owner: root
      group: root
      mode: 0600
      force: yes
      
  - name: ssh.yml - SSH enabled and running
    service:
      name: ssh
      enabled: true
      state: started
