# Ansible Playbook 
#
# Ensure Software Patches Installed
#

---
- name: apt_update.yml - Set Tags
  tags:
  - apt_update 
  block:

  - name: upgrade all packages
    apt:
      name: '*'
      state: latest
