---
  - name: Copy bashrc
    copy:
      src: ../files/bashrc
      dest: /home/erik/.bashrc
      owner: erik
      group: erik
      mode: 0644
  - name: Install the packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - vim-common
      - rkhunter
  - name: Copy vimrc
    copy:
      src: ../files/vimrc
      dest: /home/erik/.vimrc
      owner: erik
      group: erik
      mode: 0644
  - name: Create bin Directory
    file: 
      path: /home/erik/bin
      state: directory
      owner: erik
      group: erik
      mode: 0755
  - name: Copy morning script
    copy:
      src: ../files/morning.sh
      dest: /home/erik/bin/morning.sh
      owner: erik
      group: erik
      mode: 0755
