# Ansible Playbook
# Reviewed: 04/21/21
# DNS Update
#
# For:
# - rhel7

---
- name: dns_update.yml - Create rdp_nsupdate
  copy:
    src: ../files/el7/cron.daily/rdp_nsupdate
    dest: /etc/cron.daily/rdp_nsupdate
    owner: root
    group: root
    mode: 0755

- name: dns_update.yml - latest bind-utils version installed
  yum:
    name: bind-utils
    state: present

- name: dns_update.yml - Run It!
  shell: /etc/cron.daily/rdp_nsupdate
  args:
    warn: False
  changed_when: False
