# Ansible Playbook
# Reviewed: 04/21/21
# Verify firewalld Enabled
#
# For:
# - rhel7

---
- name: firewall-firewalld.yml - Latest firewall version installed
  yum:
    name: firewalld
    state: present
  ignore_errors: yes

- name: firewall-firewalld.yml - Firewalld enabled and running
  service:
    name: firewalld
    enabled: true
    state: started

- name: firewall-firewalld.yml - Set Default firewalld Zone for Incoming Packets
  copy:
    src: ../files/el7/etc/firewalld/firewalld.conf
    dest: /etc/firewalld/firewalld.conf
    owner: root
    group: root
    mode: 0644

- name: firewall-firewalld.yml - Set firewall rule to allow ssh
  firewalld:
    zone: public
    service: ssh
    permanent: true
    state: enabled

#- name: firewall-firewalld.yml - Configure rate limiting direct rule
#  command: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j INPUT_ZONES