---
- name: fstab_settings.yml - modify fstab bind tmp
  mount:
    path: /tmp
    src: /var/tmp
    fstype: none
    opts: bind
    state: present

- name: fstab_settings.yml - modify fstab bind tmp
  mount:
    path: /dev/shm
    src: tmpfs
    fstype: tmpfs
    opts: defaults,nosuid,nodev,noexec
    state: present
