# Ansible Playbook
# Reviewed: 04/21/21
# Verify Integrity with AIDE
#
# For:
# - rhel7

---
- name: install_AIDE.yml - Ensure aide is installed
  yum:
    name:
      - aide
    state: present
    disable_gpg_check: yes
  ignore_errors: yes

- name: install_AIDE.yml - Initialize AIDE
  command: /usr/sbin/aide --init

- name: install_AIDE.yml - copy aide-check
  copy:
    src: ../files/el7/etc/cron.daily/aide
    dest: /etc/cron.daily/
    owner: root
    group: root
    mode: 0750

- name: install_AIDE.yml - Edit aide.conf
  lineinfile:
    path: /etc/aide.conf
    backup: yes
    insertafter: '^ALLXTRAHASHES ='
    line: 'ALL = p+i+n+u+g+s+m+S+sha512+acl+xattrs'

- name: install_AIDE.yml - Set bin to all/sbin
  lineinfile:
    path: /etc/aide.conf
    backrefs: yes
    regexp: '^/bin/    CONTENT_EX'
    line: '/bin/    ALL'

- name: install_AIDE.yml - Set sbin to all
  lineinfile:
    path: /etc/aide.conf
    backrefs: yes
    regexp: '^/sbin/   CONTENT_EX'
    line: '/sbin/   ALL'
