# Ansible Playbook
# Reviewed: 04/21/21
# Install VA CRISP Packages
#
# For:
# - rhel7

---
- name: install_v2s.yml - Create BES Client Directory
  file:
    path: /etc/opt/BESClient
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install_v2s.yml - install Bigfix
  yum:
    name: BESAgent
    state: present
    disable_gpg_check: yes
    disable_excludes: main
  ignore_errors: yes
  when: rhel__os == "rhel7"

- name: install_v2s.yml - Set firewall UDP rule to allow Bigfix
  firewalld:
    zone: public
    port: 52311/udp
    permanent: true
    state: enabled
  when: rhel__os == "rhel7"

- name: install_v2s.yml - Set firewall TCP rule to allow Bigfix
  firewalld:
    zone: public
    port: 52311/tcp
    permanent: true
    state: enabled
  when: rhel__os == "rhel7"

- name: install_v2s.yml - install Encase
  yum:
    name: encase
    state: present
    disable_gpg_check: yes
  ignore_errors: yes
  when: rhel__os == "rhel7"

- name: install_v2s.yml - install snmp
  yum:
    name: net-snmp
    state: present
    disable_gpg_check: yes
  ignore_errors: yes
