# Ansible Playbook
# Reviewed: 04/21/21
# Configure Logging
#
# For:
# - rhel7

---
- name: logging.yml - Create sudo config file
  copy:
    content: "local2.debug /var/log/sudo.log\n"
    dest: /etc/rsyslog.d/sudo.conf
    owner: root
    group: root
    mode: 0644

- name: logging.yml - Log all sudo actions Comment
  lineinfile:
    path: /etc/sudoers
    insertafter: "# %users  localhost=/sbin/shutdown -h now"
    line: '#Added by VA CRISP'

- name: logging.yml - Log all sudo actions Comment 2
  lineinfile:
    path: /etc/sudoers
    insertbefore: "#Added by VA CRISP"
    line: '##'

- name: logging.yml - Log all sudo actions
  lineinfile:
    path: /etc/sudoers
    insertafter: "#Added by VA CRISP"
    line: 'Defaults logfile=/var/log/sudo.log,loglinelen=0'

- name: logging.yml - edit sudoers logrotate file
  blockinfile:
    path: /etc/logrotate.d/sudoers
    create: yes
    backup: yes
    marker: "## {mark} Added for VA CRISP"
    owner: root
    group: root
    mode: 0644
    content: |
      /var/log/sudo.log {
              weekly
              missingok
              rotate 4
              compress
              delaycompress
              copytruncate
              minsize 100k
      }
- name: logging.yml - Edit rsyslog to add daemon logging comment
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "local7.*                                                /var/log/boot.log"
    line: '#Added by VA CRISP'

- name: logging.yml - Edit rsyslog to add daemon logging comment
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "#Added by VA CRISP"
    line: 'daemon.*                                                /var/log/messages'

- name: logging.yml - Daily rotate comment
  lineinfile:
    path: /etc/logrotate.conf
    backrefs: yes
    regexp: '^# rotate log files weekly'
    line: '# rotate log files daily'

- name: logging.yml - Logfile permissions fixing script
  copy:
    src: ../files/el7/log_perms.sh
    dest: /root/log_perms.sh
    owner: root
    group: root
    mode: 0755
  changed_when: False

- name: logging.yml - Run logfile permissions script
  shell: /root/log_perms.sh
  changed_when: False

- name: logging.yml - Delete the script
  file:
    path: /root/log_perms.sh
    state: absent
  changed_when: False
