# Ansible Playbook
# Reviewed: 04/21/21
# Disable Kernel Modules
#
# For:
# - rhel7

---
- name: modprobe_crisp.yml - Copy crisp.conf to modprobe.d
  copy:
    src: ../files/el7/etc/modprobe.d/crisp.conf
    dest: /etc/modprobe.d/crisp.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
