# Ansible Playbook
# RReviewed: 04/21/21
# Ensure Software Patches Installed
#
# For:
# - rhel7

---
- name: yum_update.yml - Install the STIG packages
  yum:
    name:
      - tcp_wrappers
      - screen
      - tmux
      - psmisc
      - katello-host-tools-tracer
      - atop
      - htop
      - nmap-ncat.x86_64
      - nmap.x86_64
      - bash-completion.noarch
      - net-tools
      - nc
      - wget
      - yum-utils
      - yum-plugin-security
      - audispd-plugins
      - audit
      - deltarpm
      - dstat
      - dracut-fips
      - expect
      - kernel-doc
      - net-snmp
      - net-snmp-utils
      - ntp
      - mlocate
      - openscap
      - open-vm-tools
      - rsyslog
      - scap-security-guide
      - sysstat
      - system-storage-manager
      - tree
      - vim
      - vim-enhanced
      - dhclient
      - bash-completion.noarch
      - puppet-agent
      - rsyslog
      - katello-host-tools-tracer
      - katello-host-tools-fact-plugin
      - katello-host-tools
      - katello-agent
      - sos
      - lsof
      - strace
      - tcpdump
      - bind-utils
      - pam_pkcs11
    state: present
    disable_gpg_check: yes
  ignore_errors: yes

- name: yum_update.yml - Get the latest certs
  yum:
    name: http://oitphcmulrep6.r02.med.va.gov/repo/0/x86_64/VACerts/va-certs-1.0.1-2.noarch.rpm
    state: present

- name: yum_update.yml - upgrade all packages
  yum:
    name: '*'
    state: latest
    disable_gpg_check: yes
  ignore_errors: yes