# Ansible Playbook 
#
# Cron Install and setup
#
# For:
# - centos6
# - centos7

---
- name: cron_settings - latest crond version installed
  yum:
    name: cronie
    state: latest

- name: cron_settings - crond enabled and running
  service:
    name: crond
    enabled: true
    state: started

- name: cron_settings - Delete cron.deny
  file: path=/etc/cron.deny
    state=absent

- name: cron_settings - Delete cron.at
  file: path=/etc/at.deny
    state=absent

- name: cron_settings - Create cron.allow
  copy:
    content: "root\n"
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0644

- name: cron_settings - Create at.allow
  copy:
    content: "root\n"
    dest: /etc/at.allow
    owner: root
    group: root
    mode: 0644
