# Ansible Playbook 
# Erik van Oudheusden erik.vanoudheusden@va.gov - 28 Sep 2017
#
# Disable KDump Kernel Crash Analyzer (kdump)
#
# For:
# - centos6
# - centos7

---
- name: disable_kdump - Stop the kdump service and disable
  service:
    name: kdump
    enabled: no
    state: stopped

- name: disable_kdump - CRISP Comment
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: "#@student        -       maxlogins       4"
    line: '#Added by KJETT Security'

- name: disable_kdump - Disable Core Dumps for All Users
  lineinfile:
    path: /etc/security/limits.conf
    insertbefore: "# End of file"
    line: '*     hard   core    0'
