---
- name: disableNetManager - Check if NetworkManager is present
  command: "rpm -q NetworkManager"
  args:
    warn: False
  register: nm
  changed_when: False
  failed_when: nm.rc >= 2

- block:
  - name: disableNetManager - Stop if running
    service:
      name: NetworkManager
      state: stopped

  - name: disableNetManager - Disable 
    service:
      name: NetworkManager
      enabled: no
  when: nm.rc == 0
