# Ansible Playbook 
#
# Verify Permissions on Important Files and Directories
#
# For:
# - centos6
# - centos7

---
- name: file_permissions - Shadow File
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0000

- name: file_permissions - Group File
  file:
    path: /etc/group
    owner: root
    group: root
    mode: 0644

- name: file_permissions - Password File
  file:
    path: /etc/passwd
    owner: root
    group: root
    mode: 0644

- name: file_permissions - Grub File
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: 0600
  when: rhel__os == "centos7"

- name: file_permissions - Verify that System Executables Have Root Ownership
  command: /bin/find /bin/ /usr/bin/ /usr/local/bin/ /sbin/ /usr/sbin/ /usr/local/sbin/ /usr/libexec ! -user root -execdir chown root {} \;
  when: rhel__os == "centos6"
