# Ansible Playbook 
#
# Ensure Red Hat GPG Key Installed
#
# For:
# - rhel6
# - rhel7

---
- name: gpg_check_enabled - Check existence of yum
  stat:
    path: /etc/yum.conf
  register: yum_config_file
  check_mode: no

- name: gpg_check_enabled - Ensure GPG check is globally activated (yum)
  ini_file:
    dest: "{{item}}"
    section: main
    option: gpgcheck
    value: 1
    create: False
  with_items: "/etc/yum.conf"
  tags:
    - ensure_gpgcheck_globally_activated
    - high
    - CCE-26989-4

- name: gpg_check_enabled - add additional gpg checks comment
  lineinfile:
    backup: yes
    path: /etc/yum.conf
    line: '#Added by KJETT Security'

- name: gpg_check_enabled - add additional local gpg package checks
  lineinfile:
    path: /etc/yum.conf
    line: 'localpkg_gpgcheck=1'

- name: gpg_check_enabled - add additional cleaning
  lineinfile:
    path: /etc/yum.conf
    line: 'clean_requirements_on_remove=1'
