# Ansible Playbook 
#
# Configure Logging
#
# For:
# - centos6
# - centos7

---
- name: logging - Create sudo config file
  copy:
    content: "local2.debug /var/log/sudo.log\n"
    dest: /etc/rsyslog.d/sudo.conf
    owner: root
    group: root
    mode: 0644

- name: logging - Log all sudo actions Comment
  lineinfile:
    path: /etc/sudoers
    insertafter: "# %users  localhost=/sbin/shutdown -h now"
    line: '#Added by KJETT Security'

- name: logging - Log all sudo actions Comment 2
  lineinfile:
    path: /etc/sudoers
    insertbefore: "#Added by KJETT Security"
    line: '##'

- name: logging - Log all sudo actions
  lineinfile:
    path: /etc/sudoers
    insertafter: "#Added by KJETT Security"
    line: 'Defaults logfile=/var/log/sudo.log,loglinelen=0'

- name: logging - edit sudoers logrotate file
  blockinfile: 
    path: /etc/logrotate.d/sudoers
    create: yes
    backup: yes
    marker: "## {mark} Added for KJETT Security"
    owner: root
    group: root
    mode: 0644
    content: |
      /var/log/sudo.log {
              weekly
              missingok
              rotate 4
              compress
              delaycompress
              copytruncate
              minsize 100k
      }
- name: logging - Edit rsyslog to add daemon logging comment
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "local7.*                                                /var/log/boot.log"
    line: '#Added by VA CRISP'

- name: logging - Edit rsyslog to add daemon logging comment
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "#Added by VA CRISP"
    line: 'daemon.*                                                /var/log/messages'

- name: logging - Daily rotate comment
  lineinfile:
    path: /etc/logrotate.conf
    backrefs: yes
    regexp: '^# rotate log files weekly'
    line: '# rotate log files daily'

- name: logging - Daily rotate setting
  lineinfile:
    path: /etc/logrotate.conf
    backrefs: yes
    regexp: '^weekly'
    line: 'daily'
  changed_when: False
