# Ansible Playbook 
#
# Prevent Log In to Accounts With Empty Password
#
# For:
# - centos6
# - centos7

---
- name: no_empty_password_auth - Edit system-auth
  shell: |
    [ ! -f /etc/pam.d/system-auth ] && exit 2
    if grep '\<nullok\>' /etc/pam.d/system-auth &>/dev/null; then
        sed -i 's/\<nullok\>//g' /etc/pam.d/system-auth
        exit 100
    fi
  register: r
  changed_when: r.rc == 100
  failed_when: r.rc != 0 and r.rc != 100
  args:
    warn: False
