# Ansible Playbook 
#
# 6.14.18 Configure Postfix
#
# For:
# - centos6
# - centos7

---
- name: postfix - latest postfix version installed
  yum:
    name: postfix
    state: latest

- name: postfix - Postfix enabled and running
  service:
    name: postfix
    enabled: true
    state: started

- name: postfix - restrict to ipv4
  lineinfile:
    path: /etc/postfix/main.cf 
    backrefs: yes
    regexp: '^inet_protocols = all'
    line: 'inet_protocols = ipv4'

- name: postfix - Add Comment
  lineinfile:
    path: /etc/postfix/main.cf 
    insertafter: 'readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES'
    line: 'smtpd_client_restrictions = permit_mynetworks, reject'
