# Ansible Playbook 
#
# For:
# - centos6
# - centos7

---
- name: user_settings - Verify /etc/default/useradd INACTIVE
  lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE='
    line: 'INACTIVE=90'

- name: user_settings - Verify /etc/default/useradd EXPIRE
  lineinfile:
    path: /etc/default/useradd
    regexp: '^EXPIRE='
    line: 'EXPIRE='
  