# Ansible Playbook 
#
# Verify and Correct File Permissions with RPM
#
# For:
# - centos6
# - centos7

---
- name: "verify_permissions_with_rpm - Read list of files with incorrect permissions"
  shell: "rpm -Va | grep '^.M' | sed -r 's;^.*\\s+(.+);\\1;g'"
  args:
    warn: False
  register: files_with_incorrect_permissions
  failed_when: False
  changed_when: False
  check_mode: no
  tags:
    - rpm_verify_permissions
    - high
    - CCE-27209-6

- name: "verify_permissions_with_rpm - Correct file permissions with RPM"
  shell: "rpm --setperms $(rpm -qf '{{item}}')"
  args:
    warn: False
  with_items: "{{ files_with_incorrect_permissions.stdout_lines }}"
  when: files_with_incorrect_permissions.stdout_lines | length > 0
  tags:
    - rpm_verify_permissions
    - high
    - CCE-27209-6		
