# Ansible Playbook
# Reviewed: 01/07/22
# added tags 01/07/22
#
# For:
# - rhel9

---
- name: modprobe_crisp.yml - Set Tags
  tags:
  - modprobe_crisp 
  block:

  - name: modprobe_crisp.yml - Copy crisp.conf to modprobe.d
    copy:
      src: ../files/el9/etc/modprobe.d/crisp.conf
      dest: /etc/modprobe.d/crisp.conf
      backup: yes
      owner: root
      group: root
      mode: 0644
