# Ansible Playbook
# Reviewed: 01/07/22
# added tags 01/07/22
#
# For:
# - rhel9
---
- name: passwd_setting.yml - Set Tags
  tags:
  - passwd_setting 
  block:

  - name: passwd_setting.yml - copy rsyslog.conf
    copy:
      src: ../files/el9/etc/security/pwquality.conf
      dest: /etc/security/pwquality.conf
      backup: yes
      owner: root
      group: root
      mode: 0644

  - name: passwd_setting.yml - copy login.defs
    copy:
      src: ../files/el9/etc/login.defs
      dest: /etc/login.defs
      backup: yes
      owner: root
      group: root
      mode: 0644

  - name: passwd_setting.yml - copy password-auth-va
    copy:
      src: ../files/el9/etc/pam.d/password-auth-va
      dest: /etc/pam.d/password-auth-va
      owner: root
      group: root

  - name: passwd_setting.yml - Create sym link for password-auth
    file:
      src: /etc/pam.d/password-auth-va
      dest: /etc/pam.d/password-auth
      owner: root
      group: root
      state: link
      force: yes

  - name: passwd_setting.yml - copy system-auth-va
    copy:
      src: ../files/el9/etc/pam.d/system-auth-va
      dest: /etc/pam.d/system-auth-va
      owner: root
      group: root
      backup: yes
      force: yes

  - name: passwd_setting.yml - Create sym link for password-auth
    file:
      src: /etc/pam.d/system-auth-va
      dest: /etc/pam.d/system-auth
      owner: root
      group: root
      state: link
      force: yes

  - name: passwd_setting.yml - Copy faillock.conf
    copy:
      src: ../files/el9/etc/security/faillock.conf
      dest: /etc/security/faillock.conf
      backup: yes
      owner: root
      group: root
      mode: 0644
