# Ansible Playbook
# Reviewed: 01/07/22
# added tags 01/07/22
#
# For:
# - rhel9

---
- name: verify_permissions_with_rpm.yml - Set Tags
  tags:
  - verify_permissions_with_rpm 
  block:

  - name: verify_permissions_with_rpm.yml - Read list of files with incorrect permissions
    command: rpm -Va --nodeps --nosignature --nofiledigest --nosize --nomtime --nordev
      --nocaps --nolinkto --nouser --nogroup
    args:
      warn: false
    register: files_with_incorrect_permissions
    failed_when: files_with_incorrect_permissions.rc > 1
    changed_when: false
    check_mode: false

  - name: verify_permissions_with_rpm.yml - Create list of packages
    command: rpm -qf "{{ item }}"
    args:
      warn: false
    with_items: '{{ files_with_incorrect_permissions.stdout_lines | map(''regex_findall'',
      ''^[.]+[M]+.* (\/.*)'', ''\1'') | map(''join'') | select(''match'', ''(\/.*)'')
      | list | unique }}'
    register: list_of_packages
    changed_when: false
    check_mode: false
    when: (files_with_incorrect_permissions.stdout_lines | length > 0)

  - name: verify_permissions_with_rpm.yml - Correct file permissions with RPM
    command: rpm --setperms '{{ item }}'
    args:
      warn: false
    with_items: '{{ list_of_packages.results | map(attribute=''stdout_lines'') | list
      | unique }}'
    when: (files_with_incorrect_permissions.stdout_lines | length > 0)
  