# Ansible Playbook
# Reviewed: 01/07/22
# added tags 01/07/22
#
# For:
# - rhel9

---
- name: verify_hashes_with_RPM.yml - Set Tags
  tags:
  - verify_hashes_with_RPM 
  block:

  - name: verify_hashes_with_RPM.yml - Set fact Package manager reinstall command (yum)
    set_fact:
      package_manager_reinstall_cmd: yum reinstall -y
    when: ansible_distribution == "RedHat"

  - name: verify_hashes_with_RPM.yml - Read files with incorrect hash
    shell: "rpm -Va | grep -E '^..5.* /(bin|sbin|lib|lib64|usr)/' | sed -r 's;^.*\\s+(.+);\\1;g'"
    args:
      warn: False
    register: files_with_incorrect_hash
    changed_when: False
    when: package_manager_reinstall_cmd is defined
    check_mode: no

  - name: verify_hashes_with_RPM.yml - Reinstall packages of files with incorrect hash
    shell: "{{package_manager_reinstall_cmd}} $(rpm -qf '{{item}}')"
    args:
      warn: False
    with_items: "{{ files_with_incorrect_hash.stdout_lines }}"
    when: package_manager_reinstall_cmd is defined and (files_with_incorrect_hash.stdout_lines | length > 0)
