# .bashrc

# keep from going insane when referencing the info pages
alias info="pinfo"
alias cls="clear"

# see what i'm looking for
export GREP_COLOR="32"
alias grep="grep --color"

# FiX up less
export LESS="-FiX"

# make sure everything uses less
export PAGER="less -FiX"

# make sure vim is used for editing stuff
export EDITOR="vim"

# set up readline preferences
export INPUTRC="~/.inputrc"
grep -qs "editing-mode" ~/.inputrc &> /dev/null || echo "set editing-mode vi" >> ~/.inputrc

# use text-mode browser whenever possible
export BROWSER="elinks"

# always use ssh for rsync'ing
export RSYNC_RSH="ssh"

# history options
# 1st, don't put successive, duplicate commands in history file
export HISTIGNORE="&"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10000

# 2nd, append each shell's history to my main history file on exit
shopt -s histappend

# just stuff I like
alias ssh='ssh -Y -C'
alias ls='ls -lh'
alias xclock='xclock -digital -update 1'
alias df='df -Ph'
alias exit='clear && exit'

# dummy-check before destroying a file (after all, i can always use -f )
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -iv"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#Check if we need a reboot
if [ -f /var/run/reboot-required ] 
then
    echo "[*** Hello $USER, you must reboot your machine ***]"
fi

# Add Date and Time to History
export HISTTIMEFORMAT="%F %T:  "