# Ansible Playbook 
#
---
- name: Clean Media Directory
  hosts: all
  tasks:

    - name: clean_media.yml - remove exif data
      command: exiftool -progress -r -overwrite_original -all= -copyright="NONEYA LLC" /mnt/share/Tmp/Clean
      