
---
- name: dnf_update.yml - Set Tags
  hosts: all
  tags:
  - dnf_update 
  block:
  tasks:

  - name: dnf_update.yml - upgrade all packages
    dnf:
      name: '*'
      state: latest
    #ignore_errors: yes

    