# Ansible Playbook 
# Erik van Oudheusden erik.vanoudheusden@va.gov
# Reviewed: 01/09/20
# Install LibreNMS Service Checks

---
- name: Install LibreNMS Plugins
  hosts: all
  tasks:
  - name: Install LibreNMS MRPE binary
    copy:
      src: files/check_mk_agent
      dest: /usr/bin/check_mk_agent
      owner: root
      group: root 
      mode: 755

  - name: Install LibreNMS MRPE service
    copy:
      src: files/check_mk@.service
      dest: /etc/systemd/system
      owner: root
      group: root 
      mode: 755

  - name: Copy LibreNMS MRPE service
    copy:
      src: files/check_mk.socket
      dest: /etc/systemd/system
      owner: root
      group: root 
      mode: 755

  #- name: Create App Plugin Directory
  #  file: 
  #    path: /usr/lib/check_mk_agent/plugins
  #    state: directory
  #    owner: root 
  #    group: root 
  #    recurse: yes
  #    mode: 0755

  #- name: Create Check Directory 
  #  file: 
  #    path: /usr/lib/check_mk_agent/local
  #    state: directory
  #    owner: root 
  #    group: root
  #    recurse: yes 
  #    mode: 0755

  - name: Create Plugin Directory 
    file: 
      path:  /usr/lib64/nagios/plugins/
      state: directory
      owner: root 
      group: root 
      recurse: yes
      mode: 0755

  - name: Install the plugins
    apt:
      name:
        - nagios-plugins
        - nagios-nrpe-server

  - name: Create Config Directory 
    file: 
      path:  /etc/check_mk/
      state: directory
      owner: root 
      group: root 
      mode: 0755

  - name: copy mrpe conf file
    copy:
      src: files/mrpe.cfg
      dest:  /etc/check_mk/mrpe.cfg
      owner: root 
      group: root 
      mode: 0755

  - name: copy mrpe conf file
    copy:
      src: files/octo-nrpe.sh
      dest:  /usr/lib/nagios/plugins/octo-nrpe.sh
      owner: root 
      group: root 
      mode: 0755

  - name: Force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: MRPE service enabled and running
    service:
      name: check_mk.socket
      enabled: true
      state: started

